# Generated by Django 2.2.12 on 2021-06-30 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0003_collect'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Collect',
        ),
    ]
