# Generated by Django 2.2.12 on 2021-06-30 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0006_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
