# Generated by Django 2.2.12 on 2021-06-30 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0008_auto_20210630_1806'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Collectt',
            new_name='Example',
        ),
    ]
