# Generated by Django 2.2.12 on 2021-07-01 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0010_auto_20210630_1808'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=11)),
                ('json_dual', models.TextField(blank=True, default='n')),
                ('rate', models.IntegerField(default=1)),
                ('video_title', models.TextField(blank=True, default='n')),
            ],
        ),
        migrations.DeleteModel(
            name='ExCollect',
        ),
    ]
